version: "3.9"
services:
  api:
    build:
      dockerfile: docker/api/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis-db
    env_file:
      - .env
    ports:
      - 8080:8080

  redis-db:
    image: "redis/redis-stack:latest"
    ports:
      - "6379:6379"