openapi: 3.0.3
info:
  title: Конвертер валют
  description: |-
tags:
  - name: /convert
    description: Перевод из одной валюты в другую
   
  - name: /database
    description: мердж
components:
  schemas:
    convertRequestGetBody:
        type: object
        properties:
          from:
            type: string
            format: string
            example: USD
          to:
            type: string
            format: string
            example: RUB
          amount:
            type: float
            format: float
            example: 10
    databaseRequestPostBody:
        type: object
        properties:
          merge:
            type: int
            format: int64
            example: 1
paths:
  /convert?from={from}&to={to}&amount={amount}:
    get:
      tags:
        - convertRequestGetBody
      parameters:
        - name: from
          in: query
          required: true
          schema:
            type: string
        - name: to
          in: query
          required: true
          schema:
            type: string
        - name: amount
          in: query
          required: true
          schema:
            type: float

          
       

